---
- name: "PHP | Add PPA php5.6 repo"
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: "PHP | Install PHP-FPM and dependencies"
  apt: name=php5-fpm state=latest install_recommends=yes update_cache=yes
  notify: "restart php5-fpm"

- name: "PHP | Config php and php-fpm"
  template: src={{ item }} dest=/etc/php5/fpm/{{ item }}
  with_items:
    - php.ini
    - php-fpm.conf
  notify: "restart php5-fpm"

- name: "PHP | Config php-fpm pool"
  template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  notify: "restart php5-fpm"
